# Puerto que Railway asigna automáticamente para que la aplicación Spring Boot escuche las peticiones en producción
# PORT RAILWAY
server.port=${PORT}

# Configuración de conexión a la base de datos PostgreSQL alojada en Railway
# DATABASE RAILWAY
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=hAVyteCbmBqOLrAfYvNILgldsaTnrNZZ
spring.datasource.driver-class-name=org.postgresql.Driver

# Ruta donde el sistema almacenará los archivos subidos por los usuarios (imágenes, documentos, etc.)
# UPLOADS
upload.path=${UPLOAD_PATH}

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

#correo
mail.sender.password=${MAIL_SMTP_PASSWORD}

# Credenciales necesarias para integrar el sistema con la API de pagos de Mercado Pago
# MERCADOPAGO
mercadopago.access_token=${MERCADOPAGO_ACCESS_TOKEN}
mercadopago.public_key=${MERCADOPAGO_PUBLIC_KEY}
spring.sql.init.mode=never

# URL donde Mercado Pago enviará notificaciones automáticas sobre el estado de los pagos (webhook)
# NOTIFICATION
#mercadopago.notification.url=${MP_NOTIFICATION_URL} comente esto por el momento por queno esta utilizandose spring.mail.host=${MAIL_SMTP_HOST}


spring.mail.port=${MAIL_SMTP_PORT}
spring.mail.username=${MAIL_SMTP_USERNAME}
spring.mail.password=${MAIL_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true